#!/bin/sh
realpath() {
  OURPWD=$PWD
  cd "$(dirname "$1")"
  LINK=$(readlink "$(basename "$1")")
  while [ "$LINK" ]; do
    cd "$(dirname "$LINK")"
    LINK=$(readlink "$(basename "$1")")
  done
  REALPATH="$PWD/$(basename "$1")"
  cd "$OURPWD"
  echo "$REALPATH"
}
me=$(realpath $0)
program=$(basename $me)
installation=$(dirname $me)
executable=$installation/opt/arangodb/bin/$program
if [ -x $executable ] ; then
  exec $executable -c "${HOME}/Library/ArangoDB-etc/${program}.conf" "$@"
fi
echo "Could not find executable ${executable}!"
exit 1
